substitutions:
  friendly_name: "ESP32 Tesla BLE"
  devicename: "esp32-tesla-ble"
  device_description: "ESP32"

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.2.2
    platform_version: 6.7.0
