substitutions:
  friendly_name: ESPHome Tesla BLE
  device_name: esphome-tesla-ble
  device_description:  M5Stack Tesla BLE

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-tesla-ble
    version: "2024.06.19"
  libraries:
    - nanopb/Nanopb@^0.4.8

packages:
  common: !include common.yml
  project: !include project.yml

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key

# sync time with home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}-ap
    password: !secret wifi_hotspot_password

captive_portal:
