external_components:
  - components: [ tesla_ble_listener, tesla_ble_car ]
    source: components

esp32_ble_tracker:
  scan_parameters:
    window: 300ms
    # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
    continuous: false
    # interval: 1s
  on_scan_end:
    - then:
        - lambda: |-
             ESP_LOGD("ble_auto", "The scan has ended!");
