external_components:
  - components: [ tesla_ble_listener, tesla_ble_car ]
    source: components

esp32_ble_tracker:
  scan_parameters:
    window: 300ms
    # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
    continuous: false
    # interval: 1s
  on_scan_end:
    - then:
        - lambda: |-
             ESP_LOGD("ble_auto", "The scan has ended!");

button:
  - platform: template
    id: ble_pair
    name: Pair BLE key
    icon: mdi:bluetooth-connect
    on_press:
      - tesla_ble_car.pair:

  - platform: template
    name: Wake up
    icon: mdi:sleep-off
    on_press:
      - tesla_ble_car.wake:

# Enable this to scan for BLE devices
# tesla_ble_listener:

ble_client:
  - mac_address: !secret ble_mac_address
    id: ble_tesla_id
    on_connect:
      then:
        - logger.log: "Connected to Tesla BLE"
    on_disconnect:
      then:
        - logger.log: "Disconnected from Tesla BLE"

tesla_ble_car:
  ble_client_id: ble_tesla_id
  id: tesla_ble_car_id

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 60s
