external_components:
  - components: [ tesla_ble_listener, tesla_ble_car ]
    source: components

esp32_ble_tracker:
  # scan_parameters:
  #   interval: 1s
  #   window: 250ms
    # continuous: false
  on_scan_end:
    - then:
        - lambda: |-
             ESP_LOGD("ble_auto", "The scan has ended!");
