name: CI

on:
  pull_request:


jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - tesla-ble-esp32-generic.yml
          - tesla-ble-m5stack-atoms3.yml
          - tesla-ble-m5stack-nanoc6.yml
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Mock secrets.yaml from example
        run: cp secrets.yaml.example secrets.yaml
      - name: Get ESPHome version
        id: get_esphome_version
        # read esphome version from requirements.txt
        run: |
          esphome_version=$(grep esphome requirements.txt | cut -d'=' -f3)
          echo "esphome_version=$esphome_version" >> "$GITHUB_OUTPUT"
      - name: Modify packages/*.yaml to use local components
        run: |
          sed -i.bak 's|source: github://yoziru/esphome-tesla-ble/components@main|source: components|' packages/client.yml && rm packages/client.yml.bak
          sed -i.bak 's|source: github://yoziru/esphome-tesla-ble/components@main|source: components|' packages/listener.yml && rm packages/listener.yml.bak
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.2.0
        with:
          yaml_file: ${{ matrix.file }}
          cache: true
          version: ${{ steps.get_esphome_version.outputs.esphome_version }}
